### ISSUE TITLE
ROC curve, AUC, and other performance stats

### ISSUE THREAD

**Issue by sstirlin** [Markus-Go/rapidminer-anomalydetection#1]
It would be very useful to have an ROC curve (and AUC) output from these algorithms.

In ELKI the last column (if it is non-numeric) is interpreted as a class label.  The smallest class is assumed to be the set of "outliers".

Thanks!

**Comment by Markus-Go** [comment]
Hi,

There is. Check out the "Generate ROC" operator. Simply feed the algorithm's output into it ..
You get the ROC values (you can plot or export) as well as AUC value based on the outlier ranking. If you prefer, you can also get precision/recall.

Regards,
 Markus.

**Comment by sstirlin** [comment]
Awesome.  I missed that.  Thanks!
