### ISSUE TITLE
trainingSet should be testSet?

### ISSUE THREAD

**Issue by sstirlin** [Markus-Go/rapidminer-anomalydetection#2]
In line 119 of the file:

rapidminer-anomalydetection/src/de/dfki/madm/anomalydetection/evaluator/kernel_based/AnomalyDetectionLibSVMEvaluator.java

shouldn't

```
        Svm.svm_predict_values(model, trainingSet[i], prob);
```

be

```
        Svm.svm_predict_values(model, testSet[i], prob);
```

?

**Comment by Markus-Go** [comment]
Actually, its the same ... 
See the function call: computeAnomalyScore(model, values, values);

I am sorry that the code is somehow confusing at some points. Actually, since it is unsupervised, there is no training/testing ;)
