### ISSUE TITLE
Python implementation and License issue

### ISSUE THREAD

**Issue by Kanatoko** [Markus-Go/rapidminer-anomalydetection#5]
Hello,

I have implemented a [HBOS python version.](https://github.com/Kanatoko/HBOS-python)
It's almost a copy of your Java code. 
What type of License and Credits should I put?
Thanks.

**Comment by Markus-Go** [comment]
Dear Kanatoko-san,
That is awesome! I had so many requests about a Python implementation. Thank you so much for your work and letting me know!

- I fixed some minor issues about Python2
- For the licence, I would suggest GNU 3 (as the original code), if you are ok with that.
- For credits, linking to the original code is totally fine. If you also could include a link to the original paper (https://www.dfki.de/web/research/publications/renameFileForDownload?filename=HBOS-KI-2012.pdf&file_id=uploads_1716) that would be perfect!

Thanks again!

**Comment by Kanatoko** [comment]
Thank you for the quick response and pull request.
GNU 3 is fine.
