### ISSUE TITLE
Can the Generate ROC operator of your extension draw the ROC curve and get the AUC?

### ISSUE THREAD

**Issue by 2994186010** [Markus-Go/rapidminer-anomalydetection#9]
I only get many pairs of  true_positive_rate value and false positive rate value as following.
![image](https://user-images.githubusercontent.com/15965075/55301891-73105a80-5471-11e9-9007-bc44b8ddda88.png)

 I want to get ROC curve and AUC. Can your extension implement these two functions?

The dataset and the process XML are in file.zip [file.zip](https://github.com/Markus-Go/rapidminer-anomalydetection/files/3027704/file.zip)

**Comment by Markus-Go** [comment]
You can directly plot the pairs using RapidMiner (Scatter plot), or export it and plot the ROC with a tool of your choice. There is also an AUC output of the ROC operator where you get the AUC value.
